name: Check for Spammy Issue Comments

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write

jobs:
  link-check:
    name: Remove suspicious links from issue comments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |

            const comment = context.payload.comment
            const { owner, repo } = context.repo

            console.log('Repository owner:', owner)
            console.log('Repository name:', repo)
            console.log('Comment body:', comment.body)

            // Regular expression to detect MediaFire links
            const mediafireLinkPattern = /https?:\/\/(www\.)?mediafire\.com\/[^\s]+/g

            // Check if the comment contains a MediaFire link
            if (mediafireLinkPattern.test(comment.body)) {
              console.log('MediaFire link found, removing it...')
              
              // Remove the MediaFire link from the comment
              const updatedBody = comment.body.replace(mediafireLinkPattern, '[Link removed for safety reasons]')
              console.log('Updated comment body:', updatedBody)

              // Edit the comment with the MediaFire link removed
              await github.rest.issues.updateComment({
                owner: owner,
                repo: repo,
                comment_id: comment.id,
                body: updatedBody
              });
            } else {
              console.log('No MediaFire link found.')
            }

            // Regular expression to detect example links
            const exampleLinkPattern = /https?:\/\/(www\.)?example\.com\/[^\s]+/g

            // Check if the comment contains an example link
            if (exampleLinkPattern.test(comment.body)) {
              console.log('Example link found, removing it...')

              // Remove the example link from the comment
              const updatedBody = comment.body.replace(exampleLinkPattern, '[Link removed for safety reasons]')
              console.log('Updated comment body:', updatedBody)

              // Edit the comment with the example link removed
              await github.rest.issues.updateComment({
                owner: owner,
                repo: repo,
                comment_id: comment.id,
                body: updatedBody
              });
            } else {
              console.log('No example link found.')
            }
